# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the Windows single-file build of the NAV updater.

Bundles:
  - .env (generated by CI from secrets)
  - dist_seed/fund_nav.db (seed DB; copied to %LOCALAPPDATA%\\FundNAV on first run)
  - all source modules reachable from app_entry.py
  - numpy/pandas/openpyxl/sqlalchemy fully (via collect_all) to avoid
    runtime "module not found" errors after numpy 2.x's _core rename

Build:
    pyinstaller nav_updater.spec --noconfirm --clean

Output:
    dist/净值跟踪更新.exe
"""

from pathlib import Path

from PyInstaller.utils.hooks import collect_all  # noqa: E402

PROJECT = Path(SPECPATH).resolve()  # noqa: F821 - PyInstaller injects SPECPATH

datas = []
binaries = []
hidden_imports = [
    "openpyxl.cell._writer",
    "xlrd",
    "lxml",
    "lxml.etree",
    "bs4",
    "chardet",
    "imapclient",
    "sqlalchemy.dialects.sqlite",
    "loguru",
    "click",
    "dotenv",
]

# Bundle anything PyInstaller's heuristics might miss for these heavyweights.
# Particularly important for numpy 2.x where numpy.core was renamed.
for pkg in ("numpy", "pandas", "openpyxl", "sqlalchemy"):
    pkg_datas, pkg_binaries, pkg_hidden = collect_all(pkg)
    datas += pkg_datas
    binaries += pkg_binaries
    hidden_imports += pkg_hidden

_env = PROJECT / ".env"
if _env.exists():
    datas.append((str(_env), "."))

_seed = PROJECT / "dist_seed" / "fund_nav.db"
if _seed.exists():
    datas.append((str(_seed), "dist_seed"))

a = Analysis(  # noqa: F821
    ["app_entry.py"],
    pathex=[str(PROJECT)],
    binaries=binaries,
    datas=datas,
    hiddenimports=hidden_imports,
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data)  # noqa: F821

exe = EXE(  # noqa: F821
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="净值跟踪更新",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
