# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the Windows single-file build of the NAV updater.

Bundles:
  - .env (generated by CI from secrets)
  - dist_seed/fund_nav.db (seed DB; copied to %LOCALAPPDATA%\\FundNAV on first run)
  - all source modules reachable from app_entry.py

Build:
    pyinstaller nav_updater.spec --noconfirm --clean

Output:
    dist/净值跟踪更新.exe
"""

from pathlib import Path

PROJECT = Path(SPECPATH).resolve()  # noqa: F821 - PyInstaller injects SPECPATH

datas = []

_env = PROJECT / ".env"
if _env.exists():
    datas.append((str(_env), "."))

_seed = PROJECT / "dist_seed" / "fund_nav.db"
if _seed.exists():
    datas.append((str(_seed), "dist_seed"))

hidden_imports = [
    # parsing
    "openpyxl",
    "openpyxl.cell._writer",
    "xlrd",
    "lxml",
    "lxml.etree",
    "bs4",
    "pandas",
    "chardet",
    # email + db
    "imapclient",
    "sqlalchemy",
    "sqlalchemy.dialects.sqlite",
    # misc
    "loguru",
    "click",
    "dotenv",
]

a = Analysis(  # noqa: F821
    ["app_entry.py"],
    pathex=[str(PROJECT)],
    binaries=[],
    datas=datas,
    hiddenimports=hidden_imports,
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data)  # noqa: F821

exe = EXE(  # noqa: F821
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="净值跟踪更新",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
